### ISSUE TITLE
Atualizar o repositório

### ISSUE THREAD

**Issue by fsantanna** [CaioSaud/EDL#1]
Verifiquei que a questão não eram faltas ou atrasos, mas o fato do seu repositório não estar atualizado, favor atualizar o repositório com todos os trabalhos e participar mais nos *commits* da dupla, em particular para os trabalhos 6 e 7.

**Comment by CaioSaud** [comment]
Nao entendi,quer que eu envie os trabalhos que estao faltando e estao no github do Lucas?

**Comment by fsantanna** [comment]
Sim.
Não achei o trabalho 4, pode indicar onde está?
att

**Comment by fsantanna** [comment]
achei
